In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
#Laplacian Function
def get_laplacian(E,n_vertices,d=False):
    L = np.zeros([n_vertices,n_vertices]) 
    Delta = np.zeros([n_vertices,n_vertices])
    A = np.zeros([n_vertices,n_vertices]) 
    for e in E: 
        Delta[e[1],e[1]] +=1
        A[e[1],e[0]] = 1
        if d==False:
            Delta[e[0],e[0]] +=1
            A[e[0],e[1]] = 1
        else:
            Delta[e[0],e[0]] +=0
            A[e[0],e[1]] = 0
    L = Delta - A
    return Delta,A,L

def get_incidenceMatrix(E,n_vertices):
    n_e = len(E)
    D = np.zeros([n_vertices,n_e])
    for e in range(n_e):
        D[E[e][0],e] = -1
        D[E[e][1],e] = 1
    return D

In [3]:
#Edge matrix for question 
E=np.array([[0,2],[0,1],[1,2],[0,3],[1,3],[2,3],[3,4],[3,5],[4,5],[5,6],[5,7],[5,8],[6,8],[6,7],[7,8],[4,9],[4,10],[4,11],[10,11],[9,10],[9,11]])


In [4]:
Delta,A,L=get_laplacian(E,12,False)

In [5]:
print(Delta)

[[3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]]


In [6]:
print(A)

[[0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.]]


In [7]:
print(L)

[[ 3. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  3. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  3. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1.  5. -1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  5. -1.  0.  0.  0. -1. -1. -1.]
 [ 0.  0.  0. -1. -1.  5. -1. -1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  3. -1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1. -1.  3. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1. -1. -1.  3.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  3. -1. -1.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0. -1.  3. -1.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0. -1. -1.  3.]]


In [8]:
import numpy as np
import numpy.linalg as linalg

A = np.array([[3,1,1],[1,2,2],[1,2,2]])
eigenValues, eigenVectors = linalg.eig(L)

idx = eigenValues.argsort()[::1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]

In [9]:
eigenValues

array([-2.97385496e-16,  4.58618735e-01,  4.58618735e-01,  4.00000000e+00,
        4.00000000e+00,  4.00000000e+00,  4.00000000e+00,  4.00000000e+00,
        4.00000000e+00,  4.00000000e+00,  6.54138127e+00,  6.54138127e+00])

In [10]:
get_incidenceMatrix(E,12)

array([[-1., -1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1., -1., -1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., -1.,  0.,  0.,  0.,  0.,
         0.,  0., -1., -1., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1., -1., -1., -1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., -1.,
        -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  